### ISSUE TITLE
Missing compile-time error handler?

### ISSUE THREAD

**Issue by rondonjon** [okonet/yaml-loader#14]
I have created a test case with an intentionally broken yaml file:

```
yaml:
    - abc
    def: 1
```

The loader is configured as suggested (chained with JSON loader).

My expectation was that this test should fail and raise a webpack error during the build, but it doesn't. 

Instead, the output file is generated; instead of the YAML content, it now contains an exception that would be thrown at runtime:

```
/***/ }),
/* 1 */
/***/ (function(module, exports) {

throw new Error("Module build failed: YAMLException: bad indentation of a mapping entry at line 3, column 5:\n        def: 1\n        ^\n    at generateError (/home/x/x/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)\n    at throwError (/home/x/x/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)\n    at readBlockMapping (/home/x/x/node_modules/js-yaml/lib/js-yaml/loader.js:1079:7)\n    at composeNode (/home/x/x/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)\n    at readDocument (/home/x/x/node_modules/js-yaml/lib/js-yaml/loader.js:1493:3)\n    at loadDocuments (/home/x/x/node_modules/js-yaml/lib/js-yaml/loader.js:1549:5)\n    at load (/home/x/x/node_modules/js-yaml/lib/js-yaml/loader.js:1566:19)\n    at Object.safeLoad (/home/x/x/node_modules/js-yaml/lib/js-yaml/loader.js:1584:10)\n    at Object.module.exports (/home/x/x/node_modules/yaml-loader/index.js:5:18)");

/***/ })
/******/ ]);
```

IMHO, this a problem, because the error is revealed and may not even be noticed before deployment.

In general, I would assume that, if an error occurs at compile-time, it should also be raised at compile-time.

**Comment by okonet** [comment]
Do you mind creating a PR?

**Comment by rondonjon** [comment]
My bad. Had a mistake in my webpack error handler. Working fine now. Sorry for the bother.
