### ISSUE TITLE
What does include: path.resolve('data') mean?

### ISSUE THREAD

**Issue by FrankFang** [okonet/yaml-loader#16]
This loader is also useful for getting a valid JSON from YML. For example:

```
// webpack.config.js
module: {
  loaders: [
    {
      test: /\.yaml$/,
      include: path.resolve('data'),
      loader: 'yaml',
    },
  ],
}
```

**Comment by spiderpug** [comment]
See http://webpack.github.io/docs/configuration.html#module-loaders :

> Each item can have these properties:
> ...
> include: An array of paths or files where the imported files will be transformed by the loader
