### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by nkt** [okonet/yaml-loader#8]
Please publish stable `1.0.0` release. Every release you changing API and breaking my projects.

**Comment by okonet** [comment]
It didn't get any breaking changes since ever but I agree it can be a 1.0.0

**Comment by nkt** [comment]
@okonet you kidding?
`0.2.0`: use `loader: 'json!yaml'`
`0.3.0`: use `loader: 'yaml'`
`0.4.0`: use `loader: 'json!yaml'` or `window.fetch`
Really? 😄 
BTW I've created my own `yml-loader`, which stable since first release.

**Comment by okonet** [comment]
If you look at json loader source code, you'll see that both strings and objects are accepted. It's always better to create your own module and publish it to npm! (In kidding btw). 

Also, all 0.x releases aren't semver compatible and can have breaking changes so you'd better pin your deps.

**Comment by okonet** [comment]
I consider this closed but will release a 1.0 soon
